version: 2.1
orbs:
  shared: indigo/shared@volatile
  python: indigo/python@volatile
jobs:
  build:
    executor:
      name: shared/default
      indigo_image_version: python:3.6.2-indigo
    steps:
      - checkout
      - run:
          name: Setup local-env and pip install
          command: |
              python -m venv local-env
              . local-env/bin/activate
              pip install -r requirements.txt
      - shared/save_workspace_cache
  release:
    executor:
      name: shared/default
      indigo_image_version: python:3.6.2-indigo
    steps:
        - shared/restore_workspace_cache
        - python/semantic_release_publish

workflows:
    version: 2
    build_and_deploy:
      jobs:
        - build:
            context: org-global
        - release:
            context: org-global
            requires:
              - build
            filters:
              branches:
                only:
                  - master
